### PR TITLE
Do not overwrite configs by default

### LINKED ISSUE #778: Upgrade to 0.9.0 removes ntfy URL
### Prerequisites

- [x] I have read [CONTRIBUTING.md](https://github.com/EFForg/rayhunter/blob/main/CONTRIBUTING.md)

### Bug Report Details

I just upgrade Rayhunter from 0.8.0 to 0.9.0 on my TPLink v0.9 and after upgrade Ntfy URL is empty. Also, I had Device Input Mode set to double tap, and after upgrade it was "reset" to disable button control.

### PR DESCRIPTION
**Pull request by untitaker**
On tplink and orbic, do not overwrite config files by default. There is
a new flag `installer orbic --reset-config` that one can use to restore
the old behavior. This fixes #778, a long-standing issue existent since
0.3.0.

The businesslogic for config file overrides is shared to some degree.
The Install trait from pinephone.rs has been moved out and renamed to
DeviceConnection for that purpose, so that `install_config` can be
shared across installers, which in turn can delegate to the trait for
running commands and copying files. This also works towards #542.

However, the pinephone and other installers have not been adapted to
support --reset-config out of fear of regressions. A future refactor by
somebody with ability to test on pinephone should probably also consider
using the same DeviceConnection impl as orbic, if possible.

### CODE REVIEW

File: installer/src/connection.rs [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+    -> impl Future<Output = Result<()>> + Send;
+}
+
+/// Check if a file exists using a DeviceConnection
+pub async fn file_exists<C: DeviceConnection>(conn: &mut C, path: &str) -> bool {
+    conn.run_command(&format!("test -f {path} && echo exists || echo missing"))
+        .await
+        .map(|output| output.contains("exists"))
+        .unwrap_or(false)
+}
```
Comment (wgreenberg) [inline installer/src/connection.rs:24]: why not just place this & `install_config` in the `DeviceConnection` trait definition?

File: installer/src/orbic.rs [hunk 2]
```diff
@@ -46,6 +47,21 @@ const PRODUCT_ID: u16 = 0xf601;
...
+impl DeviceConnection for AdbConnection<'_> {
+    async fn run_command(&mut self, command: &str) -> Result<String> {
+        adb_command(self.device, &["sh", "-c", command])
+    }
+
+    async fn write_file(&mut self, path: &str, content: &[u8]) -> Result<()> {
+        install_file(self.device, path, content).await
+    }
+}
+
```
Comment (wgreenberg) [inline installer/src/orbic.rs:64]: nitpick: maybe define this in `connection.rs` along w/ `TelnetConnection`?

File: installer/src/pinephone.rs [hunk 3]
```diff
@@ -68,6 +75,19 @@ pub async fn install() -> Result<()> {
...
+    command: &str,
+    expected_output: &str,
+) -> Result<()> {
+    let output = adb.run_command(command).await?;
+    if !output.contains(expected_output) {
+        bail!("{expected_output:?} not found in: {output}");
+    }
+    Ok(())
+}
+
```
Comment (wgreenberg) [inline installer/src/pinephone.rs:90]: i think this might also qualify as a `DeviceConnection` trait function

File: installer/src/connection.rs (hunk 1 above)
Comment (untitaker) [reply installer/src/connection.rs:24]: I believe we should keep the trait contract small, and limited to the things that actually have to work differently per device.

Eventually I would like to have this setup:

```
generic_installer.rs
tplink_installer.rs
orbic_installer.rs
```

Where generic_installer just exposes a single function that takes a `DeviceConnection`, and runs the entire installation, in a way that is consistent for all devices.

`tplink_installer.rs` would only contain a trait impl for `DeviceConnection`, to teach generic_installer how to launch commands and copy files (and probably another trait method for running the exploit), but nothing else.

In that world, `file_exists` would be internal to `generic_installer`, and `tplink_installer.rs` would not be able to override it.

File: installer/src/orbic.rs (hunk 2 above)
Comment (untitaker) [reply installer/src/orbic.rs:64]: This `AdbConnection` is supposed to be merged with the one by pinephone (also called `AdbConnection`...), and then we can move it to connection.rs. Right now I can't do that safely because I don't have a pinephone, and can't test.

When/if I refactor UZ801 to also use device connection and this impl, I'll move it.

File: installer/src/connection.rs (hunk 1 above)
Comment (wgreenberg) [reply installer/src/connection.rs:24]: fwiw i don't feel particularly strongly about this, but do you think that adding default implementations of these to the base trait increases the contract size? i guess i saw them as pretty generic functions, but maybe i'm misunderstanding the eventual goal

Comment (untitaker) [reply installer/src/connection.rs:24]: i think adding them as default impls to the trait instead of having them as freestanding functions does increase the contract size. not the obligations of the implementor, but the freedom of the implementor to override it with custom logic. I don't want that though, if it comes to the point where an implementor really has to override `file_exists` or `update_config` I think it's time to rethink the abstraction entirely.
